version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nest_postgres
    restart: always
    environment:
      POSTGRES_USER: tsdbadmin
      POSTGRES_PASSWORD: oefixu026ou6a3qr
      POSTGRES_DB: tsdb
    ports:
      - "32953:32953"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nestjs-app:
    build: .
    container_name: nxgen-backend
    restart: always
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: nqawzwlvtf.cy67vd5uxz.tsdb.cloud.timescale.com
      DATABASE_PORT: 32953
      DATABASE_USER: tsdbadmin
      DATABASE_PASSWORD: oefixu026ou6a3qr
      DATABASE_NAME: tsdb
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start

volumes:
  postgres_data: